from .sql_permission_policy import (
    SQL_PERMISSION_POLICY_CONTRACT_VERSION,
    SQLPermissionPolicyContractError,
    SQLPermissionDecision,
    SQLPermissionAction,
    SQLPermissionResourceType,
    SQLPermissionReasonCode,
    SQLPermissionPolicyRule,
    SQLPermissionPolicyRequest,
    SQLPermissionPolicyResult,
    SQLPermissionPolicyContract,
)
from .tenant_workspace_boundary import (
    TENANT_WORKSPACE_BOUNDARY_CONTRACT_VERSION,
    TenantWorkspaceBoundaryContractError,
    TenantWorkspaceBoundaryDecision,
    TenantWorkspaceBoundaryReasonCode,
    TenantWorkspaceBoundary,
    TenantWorkspaceBoundaryRequest,
    TenantWorkspaceBoundaryResult,
    TenantWorkspaceBoundaryContract,
)
from .sql_read_only_enforcement import (
    SQL_READ_ONLY_ENFORCEMENT_CONTRACT_VERSION,
    SQLReadOnlyEnforcementContractError,
    SQLReadOnlyDecision,
    SQLReadOnlyReasonCode,
    SQLReadOnlyEnforcementRequest,
    SQLReadOnlyEnforcementResult,
    SQLReadOnlyEnforcementContract,
)
from .sql_query_risk_classifier import (
    SQL_QUERY_RISK_CLASSIFIER_CONTRACT_VERSION,
    SQLQueryRiskClassifierContractError,
    SQLQueryRiskLevel,
    SQLQueryRiskSignal,
    SQLQueryRiskRequest,
    SQLQueryRiskResult,
    SQLQueryRiskClassifier,
)
from .sql_sensitive_data_policy import (
    SQL_SENSITIVE_DATA_POLICY_CONTRACT_VERSION,
    SQLSensitiveDataPolicyContractError,
    SQLSensitivityLevel,
    SQLSensitiveDataDecision,
    SQLSensitiveResourceType,
    SQLSensitiveDataReasonCode,
    SQLSensitiveDataEvaluatedVia,
    SQLSensitiveDataRule,
    SQLSensitiveDataMatch,
    SQLSensitiveDataPolicyRequest,
    SQLSensitiveDataPolicyResult,
    SQLSensitiveDataPolicyContract,
)
from .sql_pii_phi_detection import (
    SQL_PII_PHI_DETECTION_CONTRACT_VERSION,
    SQLPiiPhiDetectionContractError,
    SQLDataClass,
    SQLPiiPhiCategory,
    SQLPiiPhiDetectionSource,
    SQLPiiPhiConfidence,
    SQLPiiPhiReasonCode,
    SQLPiiPhiEvaluatedVia,
    SQLPiiPhiDeclaration,
    SQLPiiPhiMatch,
    SQLPiiPhiDetectionRequest,
    SQLPiiPhiDetectionResult,
    SQLPiiPhiDetector,
)
from .audit_event import (
    AUDIT_EVENT_CONTRACT_VERSION,
    AuditEventContractError,
    AuditCategory,
    AuditOutcome,
    AuditSeverity,
    AuditActor,
    AuditResource,
    AuditEvent,
    compute_entry_hash,
    link,
    verify_chain,
    from_permission,
    from_tenant,
    from_read_only,
    from_risk,
    from_sensitive,
    from_pii_phi,
    from_approval,  # 26.7 interlock
    from_prompt_injection,  # 26.8 interlock
    from_result_set,  # 26.9 interlock
)
from .approval_workflow import (
    APPROVAL_WORKFLOW_CONTRACT_VERSION,
    ApprovalWorkflowContractError,
    ApprovalState,
    ApprovalDecisionType,
    ApprovalCategory,
    ApprovalReasonCode,
    ApprovalDecision,
    ApprovalRequest,
    TERMINAL_STATES,
)
from . import approval_workflow  # noqa: F401  (transition fns: approval_workflow.approve, ...)
from .prompt_injection_defense import (
    PROMPT_INJECTION_DEFENSE_CONTRACT_VERSION,
    PromptInjectionDefenseContractError,
    InjectionCategory,
    InjectionSource,
    InjectionConfidence,
    InjectionDisposition,
    InjectionReasonCode,
    PromptSegment,
    InjectionMatch,
    PromptInjectionDefenseRequest,
    PromptInjectionDefenseResult,
    PromptInjectionDefenseContract,
)
from .result_set_privacy_limits import (
    RESULT_SET_PRIVACY_LIMITS_CONTRACT_VERSION,
    ResultSetPrivacyLimitsContractError,
    ResultSetLimitDisposition,
    ResultSetLimitReasonCode,
    ResultSetLimitPolicy,
    ResultSetColumnPrivacy,
    ResultSetPrivacyLimitsRequest,
    ResultSetPrivacyLimitsResult,
    ResultSetPrivacyLimitsContract,
)
# 26.10 connection credential vault — LAZY (PEP 562). Eager import here would pull
# app.evaluation (DB adapters/drivers, urllib) into every `app.security` import,
# breaking the driver-isolation invariant guarded by the forbidden-module tests
# (test_sql_read_only_enforcement / test_sql_query_risk_classifier). Defer to access.
_LAZY_CREDENTIAL_VAULT = {
    "CONNECTION_CREDENTIAL_VAULT_CONTRACT_VERSION",
    "ConnectionCredentialVaultContractError",
    "CredentialResolutionDecision",
    "CredentialCallerPurpose",
    "CredentialVaultReasonCode",
    "CredentialLeakSignal",
    "ConnectionCredentialVaultPolicy",
    "ConnectionCredentialVaultRequest",
    "ConnectionCredentialVaultResult",
    "evaluate_connection_credential_vault",
}


def __getattr__(name):
    if name in _LAZY_CREDENTIAL_VAULT:
        from . import connection_credential_vault as _ccv
        return _ccv.evaluate if name == "evaluate_connection_credential_vault" else getattr(_ccv, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


from .audit_event import from_credential_vault

__all__ = [
    "SQL_PERMISSION_POLICY_CONTRACT_VERSION",
    "SQLPermissionPolicyContractError",
    "SQLPermissionDecision",
    "SQLPermissionAction",
    "SQLPermissionResourceType",
    "SQLPermissionReasonCode",
    "SQLPermissionPolicyRule",
    "SQLPermissionPolicyRequest",
    "SQLPermissionPolicyResult",
    "SQLPermissionPolicyContract",
    "TENANT_WORKSPACE_BOUNDARY_CONTRACT_VERSION",
    "TenantWorkspaceBoundaryContractError",
    "TenantWorkspaceBoundaryDecision",
    "TenantWorkspaceBoundaryReasonCode",
    "TenantWorkspaceBoundary",
    "TenantWorkspaceBoundaryRequest",
    "TenantWorkspaceBoundaryResult",
    "TenantWorkspaceBoundaryContract",
    "SQL_READ_ONLY_ENFORCEMENT_CONTRACT_VERSION",
    "SQLReadOnlyEnforcementContractError",
    "SQLReadOnlyDecision",
    "SQLReadOnlyReasonCode",
    "SQLReadOnlyEnforcementRequest",
    "SQLReadOnlyEnforcementResult",
    "SQLReadOnlyEnforcementContract",
    "SQL_QUERY_RISK_CLASSIFIER_CONTRACT_VERSION",
    "SQLQueryRiskClassifierContractError",
    "SQLQueryRiskLevel",
    "SQLQueryRiskSignal",
    "SQLQueryRiskRequest",
    "SQLQueryRiskResult",
    "SQLQueryRiskClassifier",
    "SQL_SENSITIVE_DATA_POLICY_CONTRACT_VERSION",
    "SQLSensitiveDataPolicyContractError",
    "SQLSensitivityLevel",
    "SQLSensitiveDataDecision",
    "SQLSensitiveResourceType",
    "SQLSensitiveDataReasonCode",
    "SQLSensitiveDataEvaluatedVia",
    "SQLSensitiveDataRule",
    "SQLSensitiveDataMatch",
    "SQLSensitiveDataPolicyRequest",
    "SQLSensitiveDataPolicyResult",
    "SQLSensitiveDataPolicyContract",
    "SQL_PII_PHI_DETECTION_CONTRACT_VERSION",
    "SQLPiiPhiDetectionContractError",
    "SQLDataClass",
    "SQLPiiPhiCategory",
    "SQLPiiPhiDetectionSource",
    "SQLPiiPhiConfidence",
    "SQLPiiPhiReasonCode",
    "SQLPiiPhiEvaluatedVia",
    "SQLPiiPhiDeclaration",
    "SQLPiiPhiMatch",
    "SQLPiiPhiDetectionRequest",
    "SQLPiiPhiDetectionResult",
    "SQLPiiPhiDetector",
    "AUDIT_EVENT_CONTRACT_VERSION",
    "AuditEventContractError",
    "AuditCategory",
    "AuditOutcome",
    "AuditSeverity",
    "AuditActor",
    "AuditResource",
    "AuditEvent",
    "compute_entry_hash",
    "link",
    "verify_chain",
    "from_permission",
    "from_tenant",
    "from_read_only",
    "from_risk",
    "from_sensitive",
    "from_pii_phi",
    "from_approval",  # 26.7 interlock
    "from_prompt_injection",  # 26.8 interlock
    "from_result_set",  # 26.9 interlock
    "APPROVAL_WORKFLOW_CONTRACT_VERSION",
    "ApprovalWorkflowContractError",
    "ApprovalState",
    "ApprovalDecisionType",
    "ApprovalCategory",
    "ApprovalReasonCode",
    "ApprovalDecision",
    "ApprovalRequest",
    "TERMINAL_STATES",
    "PROMPT_INJECTION_DEFENSE_CONTRACT_VERSION",
    "PromptInjectionDefenseContractError",
    "InjectionCategory",
    "InjectionSource",
    "InjectionConfidence",
    "InjectionDisposition",
    "InjectionReasonCode",
    "PromptSegment",
    "InjectionMatch",
    "PromptInjectionDefenseRequest",
    "PromptInjectionDefenseResult",
    "PromptInjectionDefenseContract",
    "RESULT_SET_PRIVACY_LIMITS_CONTRACT_VERSION",
    "ResultSetPrivacyLimitsContractError",
    "ResultSetLimitDisposition",
    "ResultSetLimitReasonCode",
    "ResultSetLimitPolicy",
    "ResultSetColumnPrivacy",
    "ResultSetPrivacyLimitsRequest",
    "ResultSetPrivacyLimitsResult",
    "ResultSetPrivacyLimitsContract",
    "CONNECTION_CREDENTIAL_VAULT_CONTRACT_VERSION",
    "ConnectionCredentialVaultContractError",
    "CredentialResolutionDecision",
    "CredentialCallerPurpose",
    "CredentialVaultReasonCode",
    "CredentialLeakSignal",
    "ConnectionCredentialVaultPolicy",
    "ConnectionCredentialVaultRequest",
    "ConnectionCredentialVaultResult",
    "evaluate_connection_credential_vault",
    "from_credential_vault",
]
